name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      
      - name: Create env file
        run: |
          touch .env
          echo "NEXT_PUBLIC_MASTER_URL_KEY=${{ secrets.NEXT_PUBLIC_MASTER_URL_KEY }}" >> .env
          echo "DESCOPE_CLIENT_ID=${{ secrets.DESCOPE_CLIENT_ID }}" >> .env
          echo "DESCOPE_CLIENT_SECRET=${{ secrets.DESCOPE_CLIENT_SECRET }}" >> .env
      
      - name: Build and run Docker
        run: |
          docker-compose build
          docker-compose up -d